"""Documentation output writer."""

from pathlib import Path
from typing import Dict, Any

from ..graph import KnowledgeGraph, NodeType


class DocumentationWriter:
    """Writes generated documentation to files."""

    def __init__(self, output_dir: str):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def write_all(self, graph: KnowledgeGraph) -> None:
        """Write all documentation artifacts to files."""

        doc_nodes = graph.get_nodes_by_type(NodeType.DOCUMENTATION_ARTIFACT)

        if doc_nodes:
            print(f"\nWriting {len(doc_nodes)} documentation artifacts...")

            for doc_id in doc_nodes:
                doc = graph.get_node(doc_id)
                if not doc:
                    continue

                attrs = doc.get("attributes", {})
                doc_type = attrs.get("type", "Unknown")
                content = attrs.get("content", "")

                filename = f"{doc_type}.md"
                filepath = self.output_dir / filename

                with open(filepath, "w") as f:
                    f.write(f"# {doc_type}\n\n")
                    f.write(content)

                print(f"  - {filename}")
        else:
            print("\nNo LLM-generated documentation found (use --gemini-api-key for full docs)")
            print("Generating overview from graph statistics...")

        self._write_overview(graph)

    def _write_overview(self, graph: KnowledgeGraph) -> None:
        """Write overview document."""
        stats = graph.get_stats()

        content = "# System Overview\n\n"
        content += "This documentation was automatically generated by the Agentic Architecture Knowledge Management system.\n\n"

        content += "## Graph Statistics\n\n"
        content += f"Total Nodes: {stats['total_nodes']}\n\n"
        content += f"Total Edges: {stats['total_edges']}\n\n"

        content += "### Node Types\n\n"
        for node_type, count in stats['node_types'].items():
            content += f"- {node_type}: {count}\n"

        content += "\n### Edge Types\n\n"
        for edge_type, count in stats['edge_types'].items():
            content += f"- {edge_type}: {count}\n"

        filepath = self.output_dir / "Overview.md"
        with open(filepath, "w") as f:
            f.write(content)

        print(f"  - Overview.md")
